"""New Migration

Revision ID: 042c70b4b928
Revises: e5ee6b586d85
Create Date: 2023-07-03 20:35:53.476830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042c70b4b928'
down_revision = 'e5ee6b586d85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_phone_contacts_id', table_name='phone_contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_phone_contacts_id', 'phone_contacts', ['id'], unique=False)
    # ### end Alembic commands ###
