"""New Migration

Revision ID: 1a469a37607f
Revises: 74c0e17c51b5
Create Date: 2023-07-03 20:12:07.962891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a469a37607f'
down_revision = '74c0e17c51b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
