"""New Migration

Revision ID: 1e743741b6ff
Revises: 5490690faefc
Create Date: 2023-07-04 12:41:42.588467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1e743741b6ff"
down_revision = "5490690faefc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("credentials", sa.Column("username", sa.String(), nullable=False))
    op.drop_column("credentials", "login")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credentials",
        sa.Column("login", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("credentials", "username")
    # ### end Alembic commands ###
