"""New Migration

Revision ID: 2cc1668919f1
Revises: 56f974e244d4
Create Date: 2023-07-03 19:19:08.747217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc1668919f1'
down_revision = '56f974e244d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PhoneContacts', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('PhoneContacts', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('PhoneContacts', sa.Column('last_name', sa.String(), nullable=False))
    op.add_column('PhoneContacts', sa.Column('phone_number', sa.Integer(), nullable=False))
    op.add_column('PhoneContacts', sa.Column('email', sa.Integer(), nullable=False))
    op.drop_index('ix_PhoneContacts_Id', table_name='PhoneContacts')
    op.create_index(op.f('ix_PhoneContacts_id'), 'PhoneContacts', ['id'], unique=False)
    op.drop_column('PhoneContacts', 'Email')
    op.drop_column('PhoneContacts', 'FirstName')
    op.drop_column('PhoneContacts', 'PhoneNumber')
    op.drop_column('PhoneContacts', 'LastName')
    op.drop_column('PhoneContacts', 'Id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PhoneContacts', sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"PhoneContacts_Id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.add_column('PhoneContacts', sa.Column('LastName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('PhoneContacts', sa.Column('PhoneNumber', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('PhoneContacts', sa.Column('FirstName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('PhoneContacts', sa.Column('Email', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_PhoneContacts_id'), table_name='PhoneContacts')
    op.create_index('ix_PhoneContacts_Id', 'PhoneContacts', ['Id'], unique=False)
    op.drop_column('PhoneContacts', 'email')
    op.drop_column('PhoneContacts', 'phone_number')
    op.drop_column('PhoneContacts', 'last_name')
    op.drop_column('PhoneContacts', 'first_name')
    op.drop_column('PhoneContacts', 'id')
    # ### end Alembic commands ###
