"""New Migration

Revision ID: 2e8c531f011a
Revises: 7280e7dab597
Create Date: 2023-07-03 19:25:24.399974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8c531f011a'
down_revision = '7280e7dab597'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_contacts_id'), 'phone_contacts', ['id'], unique=False)
    op.drop_index('ix_PhoneContacts_id', table_name='PhoneContacts')
    op.drop_table('PhoneContacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PhoneContacts',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_index('ix_PhoneContacts_id', 'PhoneContacts', ['id'], unique=False)
    op.drop_index(op.f('ix_phone_contacts_id'), table_name='phone_contacts')
    op.drop_table('phone_contacts')
    # ### end Alembic commands ###
