"""New Migration

Revision ID: 5490690faefc
Revises: 7ffcfdc63792
Create Date: 2023-07-04 12:35:40.453247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5490690faefc"
down_revision = "7ffcfdc63792"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("credentials")
    # ### end Alembic commands ###
