"""New Migration

Revision ID: 56f974e244d4
Revises: 
Create Date: 2023-07-03 19:15:04.642557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f974e244d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PhoneContacts',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('FirstName', sa.String(), nullable=False),
    sa.Column('LastName', sa.String(), nullable=False),
    sa.Column('PhoneNumber', sa.Integer(), nullable=False),
    sa.Column('Email', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_index(op.f('ix_PhoneContacts_Id'), 'PhoneContacts', ['Id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PhoneContacts_Id'), table_name='PhoneContacts')
    op.drop_table('PhoneContacts')
    # ### end Alembic commands ###
