"""New Migration

Revision ID: 58e9dd09dd93
Revises: 1e743741b6ff
Create Date: 2023-07-04 12:50:58.801026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58e9dd09dd93"
down_revision = "1e743741b6ff"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "contacts", ["phone_number"])
    op.create_unique_constraint(None, "contacts", ["email"])
    op.create_unique_constraint(None, "credentials", ["password"])
    op.create_unique_constraint(None, "credentials", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "credentials", type_="unique")
    op.drop_constraint(None, "credentials", type_="unique")
    op.drop_constraint(None, "contacts", type_="unique")
    op.drop_constraint(None, "contacts", type_="unique")
    # ### end Alembic commands ###
