"""New Migration

Revision ID: 5d6745150d8a
Revises: 2e8c531f011a
Create Date: 2023-07-03 19:58:22.242291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6745150d8a'
down_revision = '2e8c531f011a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
