"""New Migration

Revision ID: 7280e7dab597
Revises: afeeb7198289
Create Date: 2023-07-03 19:23:45.632128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7280e7dab597'
down_revision = 'afeeb7198289'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
