"""New Migration

Revision ID: 74c0e17c51b5
Revises: e73d8c7757d1
Create Date: 2023-07-03 20:10:55.019583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c0e17c51b5'
down_revision = 'e73d8c7757d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
