"""New Migration

Revision ID: 829c44394392
Revises: abbf0afef4c3
Create Date: 2023-07-03 20:28:24.130995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '829c44394392'
down_revision = 'abbf0afef4c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
