"""New Migration

Revision ID: 97271eaf529d
Revises: 2cc1668919f1
Create Date: 2023-07-03 19:21:26.375968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97271eaf529d'
down_revision = '2cc1668919f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
