"""New Migration

Revision ID: a642effe5d2d
Revises: 042c70b4b928
Create Date: 2023-07-03 20:38:04.414833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a642effe5d2d'
down_revision = '042c70b4b928'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
