"""New Migration

Revision ID: abbf0afef4c3
Revises: d18be0fb8ef4
Create Date: 2023-07-03 20:26:15.871831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abbf0afef4c3'
down_revision = 'd18be0fb8ef4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
