"""New Migration

Revision ID: afeeb7198289
Revises: 97271eaf529d
Create Date: 2023-07-03 19:22:19.245665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afeeb7198289'
down_revision = '97271eaf529d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
