"""New Migration

Revision ID: ba4e7b92d1e9
Revises: baf8806274ed
Create Date: 2023-07-03 20:04:10.354582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4e7b92d1e9'
down_revision = 'baf8806274ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
