"""New Migration

Revision ID: cce1453609e7
Revises: 58e9dd09dd93
Create Date: 2023-07-04 13:03:50.224856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cce1453609e7"
down_revision = "58e9dd09dd93"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("credentials_password_key", "credentials", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("credentials_password_key", "credentials", ["password"])
    # ### end Alembic commands ###
