"""New Migration

Revision ID: d18be0fb8ef4
Revises: 1a469a37607f
Create Date: 2023-07-03 20:24:50.355260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd18be0fb8ef4'
down_revision = '1a469a37607f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_phone_contacts_id', table_name='phone_contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_phone_contacts_id', 'phone_contacts', ['id'], unique=False)
    # ### end Alembic commands ###
