"""New Migration

Revision ID: e5ee6b586d85
Revises: 829c44394392
Create Date: 2023-07-03 20:30:46.311772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ee6b586d85'
down_revision = '829c44394392'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_phone_contacts_id'), 'phone_contacts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phone_contacts_id'), table_name='phone_contacts')
    # ### end Alembic commands ###
