"""New Migration

Revision ID: e73d8c7757d1
Revises: 0d9382048735
Create Date: 2023-07-03 20:08:33.891684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73d8c7757d1'
down_revision = '0d9382048735'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
