"""New Migration

Revision ID: f29124e92719
Revises: ba4e7b92d1e9
Create Date: 2023-07-03 20:05:53.920321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29124e92719'
down_revision = 'ba4e7b92d1e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
